# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[plugins.lib]
local = "~/.dotfiles/lib"

[plugins.spaceship]
github = "spaceship-prompt/spaceship-prompt"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"

[plugins.base16]
github = 'chriskempson/base16-shell'

[plugins.alias-tips]
github = 'djui/alias-tips'
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"
apply = ["defer"]

[plugins.zsh-better-npm-completion]
github = "lukechilds/zsh-better-npm-completion"
apply = ["defer"]

[plugins.wifi-password]
github = "rauchg/wifi-password"
apply = ["defer"]

[templates]
defer = { value = 'zsh-defer source "{{ file }}"', each = true }
